#!/bin/bash

app=$1

if [ -z "$app" ]; then
echo "create [app_name] [github_url]"
exit 1
fi

npx create-next-app@latest $app --ts --tailwind --eslint --app --import-alias "@/*" --src-dir
dir=$(dirname $0)
cp -r -f "$dir"/prep_files/.* ./"$app"
cd ./"$app"
npm i -D husky eslint eslint-config-next eslint-config-prettier eslint-plugin-prettier eslint-plugin-react git-commit-msg-linter husky lint-staged postcss prettier @typescript-eslint/eslint-plugin
npm i husky -g
sed -i '6a"prepare": "husky",' ./package.json
npm i
npm run prepare
echo -e "\033[32;1m[SUCESSO]\033[m" 
exit 0
